detection_site/detection_site/urls.py
"""
URL-конфигурация для проекта Django.

Этот модуль определяет URL-шаблоны для проекта Django, включая интерфейс администратора,
приложение object_detection и URL для статических медиафайлов.

URL-шаблоны:
    - '/admin/': URL для интерфейса администратора Django.
    - '/object_detection/': URL-шаблоны для приложения object_detection.
    - '/': Перенаправляет на URL '/object_detection/'.
    - URL-шаблоны для медиафайлов на основе settings.MEDIA_URL и settings.MEDIA_ROOT.

Для получения дополнительной информации о конфигурации URL в Django посетите:
https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('object_detection/', include('object_detection.urls')),
    path('', RedirectView.as_view(url='/object_detection/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection_site/object_detection/urls.py
"""
URL конфигурация для приложения Object Detection.

Этот модуль определяет URL-шаблоны для приложения Object Detection, связывая каждый URL с соответствующей
видовой функцией или классовым представлением, которые обрабатывают запросы.

Attributes:
    urlpatterns (list): Список URL-шаблонов для приложения Object Detection, включая пути к различным видовым функциям.
        Каждый path() ассоциируется с соответствующей функцией представления для обработки запросов.

Примеры использования:
    Для перехода на домашнюю страницу: '/object_detection/'
    Для регистрации пользователя: '/object_detection/register/'
    Для входа пользователя: '/object_detection/login/'
    Для выхода пользователя: '/object_detection/logout/'
    Для отображения панели управления: '/object_detection/dashboard/'
    Для обработки изображения по идентификатору: '/object_detection/process/<int:feed_id>/'
    Для добавления изображения: '/object_detection/add-image-feed/'
    Для удаления изображения по идентификатору: '/object_detection/image/delete/<int:image_id>/'
    Для просмотра истории обработки: '/object_detection/detection_history/'
"""

from django.urls import path

from .views import (home, register, user_login, user_logout, dashboard, process_image_feed, add_image_feed, delete_image, \
    detection_history, detect_objects_other_model)

from django.conf import settings
from django.conf.urls.static import static
app_name = 'object_detection'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('process/<int:feed_id>/', process_image_feed, name='process_feed'),
    path('add-image-feed/', add_image_feed, name='add_image_feed'),
    path('image/delete/<int:image_id>/', delete_image, name='delete_image'),
    path('detection_history/', detection_history, name='detection_history'),
    path('detect-objects/<int:feed_id>/', detect_objects_other_model, name='detect_objects_other_model'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

detection_site/object_detection/models.py
"""
Модели для приложения Object Detection.

Этот модуль содержит определения трех моделей Django, используемых в приложении Object Detection:
- ImageFeed: Хранит информацию о загруженных изображениях пользователей.
- DetectedObject: Сохраняет результаты обнаружения объектов на изображениях.
- DetectionHistory: Хранит историю обработки изображений с обнаруженными объектами.

Attributes:
    ImageFeed (models.Model): Модель для хранения информации о загруженных изображениях.
        Связана с пользователем через внешний ключ и содержит поля для основного и обработанного изображений.

    DetectedObject (models.Model): Модель для хранения результатов обнаружения объектов на изображениях.
        Связана с ImageFeed через внешний ключ и содержит поля для типа объекта, уверенности в обнаружении и местоположения.

    DetectionHistory (models.Model): Модель для хранения истории обработки изображений с обнаруженными объектами.
        Связана с пользователем через внешний ключ и содержит поля для оригинального и обработанного изображений,
        текстового поля для сохранения обнаруженных объектов, времени создания записи и флага удаления.
"""

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class ImageFeed(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    processed_image = models.ImageField(upload_to='processed_images/', null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.image.name}"


class DetectedObject(models.Model):
    image_feed = models.ForeignKey(ImageFeed, related_name='detected_objects', on_delete=models.CASCADE)
    object_type = models.CharField(max_length=100)
    confidence = models.FloatField()
    location = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.object_type} ({self.confidence * 100}%) on {self.image_feed.image.name}"


class DetectionHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='original_images/')
    processed_image = models.ImageField(upload_to='processed_images/', blank=True, null=True)
    detected_objects = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'DetectionHistory({self.user.username}, {self.created_at})'

detection_site/object_detection/forms.py
"""
Форма для загрузки изображений в приложении Object Detection.

Этот модуль определяет форму ImageFeedForm, используемую для загрузки изображений
в приложении Object Detection.

Attributes:
    ImageFeedForm (forms.ModelForm): Форма для загрузки изображений.
        Определяет модель ImageFeed и указывает на использование поля 'image'.
        Имеет виджет для выбора файлов типа изображений и текст помощи для пользователей.
"""

from django import forms
from .models import ImageFeed


class ImageFeedForm(forms.ModelForm):
    class Meta:
        model = ImageFeed
        fields = ['image']
        widgets = {
            'image': forms.FileInput(attrs={'accept': 'image/*'}),
        }
        help_texts = {
            'image': 'Upload an image file.',
        }

detection_site/object_detection/views.py
"""
Представления Django для приложения object_detection.

Этот модуль содержит функции представлений для управления веб-страницами и операциями пользовательского взаимодействия в приложении object_detection.

Атрибуты:
    home(request): Возвращает домашнюю страницу приложения.
    register(request): Предоставляет форму регистрации пользователей и обрабатывает её данные.
    user_login(request): Предоставляет форму входа пользователей и обрабатывает её данные.
    user_logout(request): Выход пользователя из системы.
    dashboard(request): Отображает панель управления пользователя с его загруженными изображениями.
    process_image_feed(request, feed_id): Обрабатывает изображение с заданным feed_id.
    add_image_feed(request): Предоставляет форму загрузки изображения и сохраняет его в базе данных.
    delete_image(request, image_id): Удаляет изображение из базы данных и файловой системы проекта.
    detection_history(request): Отображает историю обработанных изображений текущего пользователя.

Функции для внутреннего использования:
    pathfinder(image): Вспомогательная функция для создания пути к изображениям.
    __del_img(image): Удаляет изображение и его обработанный экземпляр из директории проекта.
    __del_duplicate_img(image): Удаляет дубликат изображения перед его обработкой.

Модули Django:
    render: Функция для рендеринга HTML-шаблонов.
    get_object_or_404: Функция для получения объекта или 404 ошибки, если объект не найден.
    redirect: Функция для перенаправления пользователя на другую страницу.
    login_required: Декоратор для защиты представлений, требующих аутентификации пользователя.

Импорты:
    os: Встроенный модуль для работы с операционной системой.
    ImageFeed, DetectionHistory: Модели данных Django для работы с изображениями и историей обработки.
    process_image: Функция для обработки изображений.
    ImageFeedForm: Форма Django для загрузки изображений.
    AuthenticationForm, UserCreationForm: Формы Django для аутентификации и регистрации пользователей.

"""

import os

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import ImageFeed, DetectionHistory
from .utils import (process_image,process_image_detect_other_model)
from .forms import ImageFeedForm
import unittest
import io
from django.http import HttpResponse


def home(request):
    """Отображает домашнюю страницу приложения."""
    return render(request, 'object_detection/home.html')


def register(request):
    """Предоставляет форму регистрации пользователей и обрабатывает её данные."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('object_detection:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'object_detection/register.html', {'form': form})


def user_login(request):
    """Предоставляет форму входа пользователей и обрабатывает её данные."""
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('object_detection:dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'object_detection/login.html', {'form': form})


@login_required
def user_logout(request):
    """Выход пользователя из системы."""
    logout(request)
    return redirect('object_detection:login')


@login_required
def dashboard(request):
    """Отображает панель управления пользователя с его загруженными изображениями."""
    image_feeds = ImageFeed.objects.filter(user=request.user)
    return render(request, 'object_detection/dashboard.html', {'image_feeds': image_feeds})


@login_required
def process_image_feed(request, feed_id):
    """Обрабатывает изображение с заданным feed_id."""
    image_feed = get_object_or_404(ImageFeed, id=feed_id, user=request.user)
    process_image(feed_id)  # Consider handling this asynchronously
    return redirect('object_detection:dashboard')


@login_required
def detect_objects_other_model(request, feed_id):
    """Совершить классификацию над изображением"""
    image_feed = get_object_or_404(ImageFeed, id=feed_id, user=request.user)

    __del_duplicate_img(image_feed)

    process_image_detect_other_model(feed_id)  # Consider handling this asynchronously
    return redirect('object_detection:dashboard')


@login_required
def add_image_feed(request):
    """Предоставляет форму загрузки изображения и сохраняет его в базе данных."""
    if request.method == 'POST':
        form = ImageFeedForm(request.POST, request.FILES)
        if form.is_valid():
            image_feed = form.save(commit=False)
            image_feed.user = request.user
            image_feed.save()
            return redirect('object_detection:dashboard')
    else:
        form = ImageFeedForm()
    return render(request, 'object_detection/add_image_feed.html', {'form': form})


def pathfinder(image):
    """Функция создания пути для изображений."""
    filename = str(image)
    filename = filename.split('/')[1]
    relative_path = 'media/images/'
    relative_path_2 = 'media/processed_images/processed_images'
    file_path = os.path.join(os.getcwd(), relative_path, filename)
    file_path_2 = os.path.join(os.getcwd(), relative_path_2, filename)
    return file_path, file_path_2, filename


def __del_img(image):
    """Удаляет изображение и его обработанный экземпляр из директории проекта."""
    file_path, file_path_2, filename = pathfinder(image)
    if os.path.isfile(file_path) and os.path.isfile(file_path_2):
        os.remove(file_path)
        os.remove(file_path_2)
    elif os.path.isfile(file_path):
        os.remove(file_path)


def __del_duplicate_img(image):
    """Удаляет дубликат изображения перед его обработкой."""
    _, file_path_2, filename = pathfinder(image)
    if os.path.isfile(file_path_2):
        os.remove(file_path_2)


@login_required
def delete_image(request, image_id):
    """Удаляет изображение из базы данных и файловой системы проекта."""
    image = get_object_or_404(ImageFeed, id=image_id, user=request.user)  # Ensuring only the owner can delete
    __del_img(image)

    DetectionHistory.objects.filter(
        user=request.user,
        image=image.image,
        processed_image=image.processed_image
    ).update(is_deleted=True)

    image.delete()
    return redirect('object_detection:dashboard')


@login_required
def detection_history(request):
    """Отображает историю обработанных изображений текущего пользователя."""
    history = DetectionHistory.objects.filter(user=request.user).order_by('-created_at')
    return render(request, 'object_detection/detection_history.html', {'history': history})

detection_site/object_detection/templates/object_detection/add_image_feed.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Add Image Feed</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Upload Image</button>
</form>
{% endblock %}

detection_site/object_detection/templates/object_detection/add_video_feed.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Add Image Feed</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Image</button>
</form>
{% endblock %}

detection_site/object_detection/templates/object_detection/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Object Detection Platform{% endblock %}</title>
    <!-- Подключение шрифтов и CSS файлов -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/ico+xml" href="{% static 'logo/favicon.ico' %}">

</head>
<body>
    <!-- Начало заголовка -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'object_detection:home' %}">Object Detection</a>
            <img src="{% static 'logo/logo_1.svg'%}" alt="Лого">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <!-- Главная страница -->
                    <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'object_detection:home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <!-- Панель управления для авторизованных пользователей -->
                    <li class="nav-item {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'object_detection:dashboard' %}">Dashboard</a>
                    </li>
                    <!-- История обнаружений для авторизованных пользователей -->
                    <li class="nav-item {% if request.resolver_match.url_name == 'detection_history' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'object_detection:detection_history' %}">Detection History</a>
                    </li>
                    <!-- Выход -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'object_detection:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <!-- Вход для неавторизованных пользователей -->
                    <li class="nav-item {% if request.resolver_match.url_name == 'login' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'object_detection:login' %}">Login</a>
                    </li>
                    <!-- Регистрация для неавторизованных пользователей -->
                    <li class="nav-item {% if request.resolver_match.url_name == 'register' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'object_detection:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <!-- Основной контент -->
    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>
    <!-- Подключение JavaScript файлов -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

detection_site/object_detection/templates/object_detection/dashboard.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Dashboard</h2>
<a href="{% url 'object_detection:add_image_feed' %}" class="btn btn-success mb-3">Add Image</a>

{% for feed in image_feeds %}
<div class="card mb-3">
    <div class="card-header">
        <a href="{% url 'object_detection:process_feed' feed.id %}" class="btn btn-secondary">Process Image</a>
        <a href="{% url 'object_detection:detect_objects_other_model' feed.id %}" class="btn btn-secondary">Process Image other model </a>
    </div>
    <div class="card-body">
        <a href="{{ feed.image.url }}" target="_blank">
            <img src="{{ feed.image.url }}" alt="Original Image" style="width: 50px; height: 50px;">
        </a>
        {% if feed.processed_image %}
        <a href="{{ feed.processed_image.url }}" target="_blank">
            <img src="{{ feed.processed_image.url }}" alt="Processed Image" style="width: 50px; height: 50px;">
        </a>
        <ul>
            {% for obj in feed.detected_objects.all %}
            <li>{{ obj.object_type }} - {{ obj.confidence|floatformat:2 }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <form action="{% url 'object_detection:delete_image' feed.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>
{% endfor %}
{% endblock %}

detection_site/object_detection/templates/object_detection/detection_history.html
{% extends 'object_detection/base.html' %}

{% block content %}
<h2>Detection History</h2>
<table class="table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Original Image</th>
            <th>Processed Image</th>
            <th>Detect Objects</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for history_item in history %}
        <tr>
            <td>{{ history_item.created_at }}</td>
            <td><img src="{{ history_item.image.url }}" alt="Original Image" style="width: 100px;"></td>
            <td>
                {% if history_item.processed_image %}
                <img src="{{ history_item.processed_image.url }}" alt="Processed Image" style="width: 100px;">
                {% else %}
                Processing not complete
                {% endif %}
            </td>
            <td>{{ history_item.detected_objects }}</td>
            <td>
                {% if history_item.is_deleted %}
                Deleted
                {% else %}
                Active
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

detection_site/object_detection/templates/object_detection/home.html
{% extends "object_detection/base.html" %}

{% block content %}
<h1>Welcome to the Object Detection Platform</h1>
<p>This is the home page of your application.</p>
<a href="{% url 'object_detection:dashboard' %}" class="btn btn-primary">Go to Dashboard</a>
{% endblock %}

detection_site/object_detection/templates/object_detection/login.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Login</button>
</form>
<a href="{% url 'object_detection:register' %}" class="btn btn-link">Register</a>
{% endblock %}

detection_site/object_detection/templates/object_detection/register.html
{% extends "object_detection/base.html" %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Register</button>
</form>
<a href="{% url 'object_detection:login' %}" class="btn btn-link">Login</a>
{% endblock %}